### ISSUE TITLE
More readable message for exceptions

### ISSUE THREAD

**Issue by arturf** [samdark/yii2-psr-log-target#15]
Right now log messages are a bit verbose. My propose is to update export method with next change:
```diff
-- $text = (string)$text;
++ $context['trace'] = explode(PHP_EOL, $text->getTraceAsString());
++ $text = $text->getMessage();
```

> `getTrace()`does not work in some cases.

Before:
```json
{
  "message": "yii\\db\\Exception: Some exception message in /home/app/components/Registry.php:64\nStack trace:\n#0 /home/vendor/yiisoft/yii2/base/BaseObject.php(109): app\\components\\Registry->init()\n#1 [internal function]: yii\\base\\BaseObject->__construct(Array)\n#2 /home/vendor/yiisoft/yii2/di/Container.php(392): ReflectionClass->newInstanceArgs(Array)\n#3 /home/vendor/yiisoft/yii2/di/Container.php(159): yii\\di\\Container->build('app\\\\components\\\\...', Array, Array)\n#4 /home/vendor/yiisoft/yii2/BaseYii.php(351): yii\\di\\Container->get('app\\\\components\\\\...', Array, Array)\n#5 /home/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\\BaseYii::createObject(Array)\n#6 /home/vendor/yiisoft/yii2/base/Module.php(742): yii\\di\\ServiceLocator->get('registry', true)\n#7 /home/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\\base\\Module->get('registry')\n#8 /home/app/modules/api/controllers/RegistryController.php(21): yii\\di\\ServiceLocator->__get('registry')\n#9 [internal function]: app\\modules\\api\\controllers\\RegistryController->actionIndex()\n#10 /home/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#11 /home/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)\n#12 /home/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('', Array)\n#13 /home/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('api/registry', Array)\n#14 /home/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#15 /home/web/index.php(20): yii\\base\\Application->run()\n#16 {main}\nAdditional Information:\nArray\n(\n)\n",
  "context": {
    "trace": []
}
}
```

After:
```json
{
  "message": "Some exception message",
  "context": {
    "trace": [
      "#0 /home/vendor/yiisoft/yii2/base/BaseObject.php(109): app\\components\\Registry->init()",
      "#1 [internal function]: yii\\base\\BaseObject->__construct(Array)",
      "#2 /home/vendor/yiisoft/yii2/di/Container.php(392): ReflectionClass->newInstanceArgs(Array)",
      "#3 /home/vendor/yiisoft/yii2/di/Container.php(159): yii\\di\\Container->build('app\\\\components\\\\...', Array, Array)",
      "#4 /home/vendor/yiisoft/yii2/BaseYii.php(351): yii\\di\\Container->get('app\\\\components\\\\...', Array, Array)",
      "#5 /home/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\\BaseYii::createObject(Array)",
      "#6 /home/vendor/yiisoft/yii2/base/Module.php(742): yii\\di\\ServiceLocator->get('registry', true)",
      "#7 /home/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\\base\\Module->get('registry')",
      "#8 /home/app/modules/api/controllers/RegistryController.php(21): yii\\di\\ServiceLocator->__get('registry')",
      "#9 [internal function]: app\\modules\\api\\controllers\\RegistryController->actionIndex()",
      "#10 /home/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
      "#11 /home/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)",
      "#12 /home/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('', Array)",
      "#13 /home/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('api/registry', Array)",
      "#14 /home/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
      "#15 /home/web/index.php(20): yii\\base\\Application->run()",
      "#16 {main}"
    ]
}
```

What do you think about this? If ok, I'll create a pull request.

**Comment by samdark** [comment]
Sounds good 👍
